---
apiVersion: v1
kind: Namespace
metadata:
  name: alameda
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evictioner
  namespace: alameda
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: alameda-evictioner-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: alameda-evictioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-evictioner-role
subjects:
- kind: ServiceAccount
  name: evictioner
  namespace: alameda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: evictioner
  name: evictioner
  namespace: alameda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evictioner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: evictioner
        deploymentconfig: evictioner
    spec:
      containers:
      - image: evictioner:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ALAMEDA_EVICTIONER_EVICTION_ENABLE
          value: "false"
        name: evictioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: evictioner
      serviceAccountName: evictioner
      terminationGracePeriodSeconds: 30
